version: "3.3"
services:
  # app:
  #   image: januus/indexer-insights:0.0.1
  #   ports:
  #     - 8081:8081
  postgres:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=db
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres:
